name: ctp
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - graphviz
  - matplotlib
  - nltk
  - numpy
  - pandas
  - plotly
  - python
  - regex
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - streamlit
